FROM python

RUN apt-get update -y
RUN apt-get install -y gcc
RUN apt-get install -y build-essential libpq-dev

RUN pip install --upgrade pip

WORKDIR /home
COPY producer_install.txt .
RUN pip install --no-cache-dir -r producer_install.txt

WORKDIR /home/Producer